version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aya_software
    ports:
      - "5432:5432"
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    #   - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    #   - ./data-dump.sql:/docker-entrypoint-initdb.d/data-dump.sql

volumes:
  db-data:
